version: '3'
services:
  frontend:
    build: .
    ports: 
      - "8089:8089"
    volumes: 
      - .:/home/node/app:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true